"""Add property settings columns

Revision ID: cd80af678b56
Revises: c73ea09ed7c8
Create Date: 2026-07-30 20:22:43.433320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd80af678b56'
down_revision = 'c73ea09ed7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notifications_is_read')
        batch_op.drop_index('idx_notifications_tenant_id')

    op.drop_table('notifications')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('receipt_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index('idx_expenses_category')
        batch_op.drop_index('idx_expenses_expense_date')
        batch_op.drop_index('idx_expenses_property_id')
        batch_op.drop_constraint('expenses_property_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'properties', ['property_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_index('idx_payments_checkout_request_id')
        batch_op.drop_index('idx_payments_payment_date')
        batch_op.drop_index('idx_payments_property_id')
        batch_op.drop_index('idx_payments_receipt_no')
        batch_op.drop_index('idx_payments_status')
        batch_op.drop_index('idx_payments_tenant_id')
        batch_op.drop_constraint('payments_water_bill_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('payments_property_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('payments_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('payments_tenant_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'properties', ['property_id'], ['id'])
        batch_op.create_foreign_key(None, 'units', ['unit_id'], ['id'])
        batch_op.drop_column('water_bill_id')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_account_prefix', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_phone_number', sa.String(length=20), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index('idx_properties_city')
        batch_op.drop_index('idx_properties_status')
        batch_op.drop_column('owner_phone_last_8')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('monthly_rent',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('deposit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index('idx_tenants_phone')
        batch_op.drop_index('idx_tenants_property_id')
        batch_op.drop_index('idx_tenants_status')
        batch_op.drop_index('idx_tenants_unit_id')
        batch_op.drop_constraint('tenants_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('tenants_property_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'units', ['unit_id'], ['id'])
        batch_op.create_foreign_key(None, 'properties', ['property_id'], ['id'])

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.alter_column('monthly_rent',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('deposit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index('idx_units_property_id')
        batch_op.drop_index('idx_units_status')
        batch_op.drop_constraint('units_property_id_unit_number_key', type_='unique')
        batch_op.drop_constraint('units_property_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'properties', ['property_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_active')
        batch_op.drop_index('idx_users_email')
        batch_op.drop_index('idx_users_role')

    with op.batch_alter_table('water_bills', schema=None) as batch_op:
        batch_op.alter_column('water_charge',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('garbage_charge',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('300'))
        batch_op.alter_column('total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index('idx_water_bills_property_id')
        batch_op.drop_index('idx_water_bills_tenant_id')
        batch_op.drop_constraint('water_bills_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('water_bills_tenant_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('water_bills_property_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'properties', ['property_id'], ['id'])
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'units', ['unit_id'], ['id'])
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('water_readings', schema=None) as batch_op:
        batch_op.alter_column('previous_reading',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('current_reading',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('units_used',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('70'))
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.drop_index('idx_water_readings_reading_date')
        batch_op.drop_index('idx_water_readings_tenant_id')
        batch_op.drop_constraint('water_readings_tenant_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_readings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('water_readings_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_water_readings_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index('idx_water_readings_reading_date', ['reading_date'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('70'))
        batch_op.alter_column('units_used',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('current_reading',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('previous_reading',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('water_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('water_bills_property_id_fkey', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('water_bills_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('water_bills_unit_id_fkey', 'units', ['unit_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('idx_water_bills_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index('idx_water_bills_property_id', ['property_id'], unique=False)
        batch_op.alter_column('total',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('garbage_charge',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('300'))
        batch_op.alter_column('water_charge',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_role', ['role'], unique=False)
        batch_op.create_index('idx_users_email', ['email'], unique=False)
        batch_op.create_index('idx_users_active', ['active'], unique=False)

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('units_property_id_fkey', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('units_property_id_unit_number_key', ['property_id', 'unit_number'])
        batch_op.create_index('idx_units_status', ['status'], unique=False)
        batch_op.create_index('idx_units_property_id', ['property_id'], unique=False)
        batch_op.alter_column('deposit',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('monthly_rent',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tenants_property_id_fkey', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('tenants_unit_id_fkey', 'units', ['unit_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('idx_tenants_unit_id', ['unit_id'], unique=False)
        batch_op.create_index('idx_tenants_status', ['status'], unique=False)
        batch_op.create_index('idx_tenants_property_id', ['property_id'], unique=False)
        batch_op.create_index('idx_tenants_phone', ['phone'], unique=False)
        batch_op.alter_column('balance',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('deposit',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('monthly_rent',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_phone_last_8', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
        batch_op.create_index('idx_properties_status', ['status'], unique=False)
        batch_op.create_index('idx_properties_city', ['city'], unique=False)
        batch_op.alter_column('address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('payment_phone_number')
        batch_op.drop_column('mpesa_account_prefix')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('water_bill_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payments_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('payments_unit_id_fkey', 'units', ['unit_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('payments_property_id_fkey', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('payments_water_bill_id_fkey', 'water_bills', ['water_bill_id'], ['id'])
        batch_op.create_index('idx_payments_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index('idx_payments_status', ['status'], unique=False)
        batch_op.create_index('idx_payments_receipt_no', ['receipt_no'], unique=False)
        batch_op.create_index('idx_payments_property_id', ['property_id'], unique=False)
        batch_op.create_index('idx_payments_payment_date', ['payment_date'], unique=False)
        batch_op.create_index('idx_payments_checkout_request_id', ['checkout_request_id'], unique=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('expenses_property_id_fkey', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_expenses_property_id', ['property_id'], unique=False)
        batch_op.create_index('idx_expenses_expense_date', ['expense_date'], unique=False)
        batch_op.create_index('idx_expenses_category', ['category'], unique=False)
        batch_op.alter_column('receipt_no',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)

    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('sent_via', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("sent_via::text = ANY (ARRAY['whatsapp'::character varying, 'sms'::character varying, 'email'::character varying, 'in_app'::character varying]::text[])", name='notifications_sent_via_check'),
    sa.CheckConstraint("type::text = ANY (ARRAY['rent_due'::character varying, 'payment_confirmed'::character varying, 'water_bill'::character varying, 'general'::character varying]::text[])", name='notifications_type_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='notifications_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notifications_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index('idx_notifications_is_read', ['is_read'], unique=False)

    # ### end Alembic commands ###
